FROM eclipse-temurin:17-jre


LABEL org.opencontainers.image.source=https://github.com/ashmithadsouza/ecommerce-deployment

WORKDIR /app

# Matches the target folder inside the product-service directory
COPY target/*.jar app.jar

# Product service port
EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]
